### ISSUE TITLE
Support explicit extensions

### ISSUE THREAD

**Issue by OliverJAsh** [pzavolinsky/ts-unused-exports#11]
Module imports can optionally be explicit about the file extension, e.g. `import 'foo.js'`. ts-unused-exports fails in this case, because it assumes the extension must be appended.

**Comment by Place1** [comment]
Just hit this problem as well. In my case i'm importing `.scss`.

**Comment by pzavolinsky** [comment]
Thanks @OliverJAsh for your contrib.

I've just pushed `ts-unused-exports@2.0.5` including Oliver's PR and also filtering for existing files that are not TS/JS (e.g. `scss`). This should solve @Place1 's issue.

Sorry for the obscene delay merging this PR.

Cheers!

**Comment by pzavolinsky** [comment]
BTW: let me know if this fixes your issues and if not, we'll reopen the issue (and add a regression test).
