### ISSUE TITLE
Does this work with javascript files?

### ISSUE THREAD

**Issue by kamok** [pzavolinsky/ts-unused-exports#114]
I'm working with a hybrid .ts and .js project, would like to know if it also interprets .js files.

**Comment by mrseanryan** [comment]
hi @kamok - as far as I know, `ts-unused-exports` is only intended for `TypeScript` files.

@pzavolinsky I think `JavaScript` files could in theory be supported, but would need a lot of tests and then modification ?

**Comment by mrseanryan** [comment]
closing - if we want to discuss more, we can open again.
