### ISSUE TITLE
Dynamic import detection producing false positives in class methods

### ISSUE THREAD

**Issue by jp7837** [pzavolinsky/ts-unused-exports#124]
a.ts:
```
export const A = 1;
export const A_unused = 2;
```
b:ts:
```
class C {
	F() {
		import("./a").then(A_imported => console.log(A_imported.A));
	}
}

export const B_unused = 0;
```
tsconfig.json:
```
{
	"compilerOptions": {
		"lib": ["ES2015", "DOM"]
	},
	"files": [
		"a.ts",
		"b.ts"
	]
}
```

**Expected**: A_unused, B_unused marked as unused
**Actual**: A, A_unused, B_unused marked as unused.

A should not be marked as unused since it's referenced in B.

**Comment by mrseanryan** [comment]
@jp7837  thanks for finding!

Hope to fix this weekend.

**Comment by jp7837** [comment]
@mrseanryan we also use a pattern consisting of a React component that performs a dynamic import, passed as a prop.  Simplified example below.  It may be fixed by the same change, but if not, I will open a new issue for that.

b.tsx:
```
const element = (
	<div
		a={import("./a").then(A_imported => {
			console.log(A_imported.A);
		})}
	/>
);
export const B_unused = 0;
```

**Comment by mrseanryan** [comment]
For covering tsx, there is a separate issue

https://github.com/pzavolinsky/ts-unused-exports/issues/127
