### ISSUE TITLE
Support dynamic imports

### ISSUE THREAD

**Issue by OliverJAsh** [pzavolinsky/ts-unused-exports#13]
TS now has support for ES dynamic imports. ts-unused-exports should support these and extract the module IDs.

**Comment by OliverJAsh** [comment]
I gave this a go, here is where I got

We are looking for call expressions with an expression kind of `ts.SyntaxKind.ImportKeyword`.

These can appear anywhere, i.e. in a module root or inner function, so we need to traverse all nodes in the graph (?). I wasn't sure how to do that efficiently.

Separately, I noticed the `SourceFile` type we get back from `ts.createSourceFile` should already have an `imports` property, but in practice in returns `undefined` 🤷‍♂️  https://github.com/Microsoft/TypeScript/blob/6997e9b7316b081f8731d131139c7d7f1bba9092/src/services/services.ts#L529

It would be good if we can outsource the work for finding imports.

**Comment by mitschmidt** [comment]
Any update on this? A feature like this would reduce the amount of false positives for our projects significantly.

**Comment by mrseanryan** [comment]
example to help think about this:

```
function renderWidget() {
  const container = document.getElementById("widget");
  if (container !== null) {
    import("./widget").then(widget => {
      widget.render(container);
    });
  }
}

renderWidget();
```

Difficulties:
- need to find the dynamic imports, which can be a statement anywhere in a function
- the containing function can itself be dead code!

**Comment by tabansal** [comment]
Do we have plans for handling dynamic imports? Or is there a way to supress warning for these kind of exports?

**Comment by mrseanryan** [comment]
Hi @tabansal - it's definitely on the cards.

In the meantime, you could try:

- disable any relevant lines that are false positives:
 ```
// ts-unused-exports:disable-next-line
```

- or use the `- - ignorePaths` option to exclude whole files from the results

**Comment by jp7837** [comment]
@mrseanryan to be clear, does this only detect default exports from dynamically imported modules?  Or would it handle any export on the module?  From your examples, would it handle:

```
Scenario: Include dynamic import as promise
  Given file "a.ts" is
    """
    export type A = 1;
    export type A_unused = 2;
    """
  And file "b.ts" is
    """
    import("./a").then(A_imported => {
    console.log(A_imported.A);
    });
    export const B_unused: A = 0
    """
  When analyzing "tsconfig.json"
  Then the result is { "b.ts": ["B_unused"], "a.ts": ["A_unused"] }
```

**Comment by mrseanryan** [comment]
Hi @jp7837 - it should handle dynamic imports of all exports.

Certainly all the test cases are covered (in the features folder).

However, if you find something we don't cover, please log an issue.

**Comment by jp7837** [comment]
@mrseanryan thanks opened #117 with details
