### ISSUE TITLE
[Regression] Dynamic imports in ternary not detected

### ISSUE THREAD

**Issue by jp7837** [pzavolinsky/ts-unused-exports#139]
Regression from 6.1.1 to 6.2.0

```
return foo
	? import("a").then(({ subA }) => new subA())
	: import("b").then(({ subB }) => new subB(id));
```

`subA` and `subB` will be not be detected as used

**Comment by jp7837** [comment]
@mrseanryan looks like a potential regression from #128

**Comment by mrseanryan** [comment]
@jp7837  thanks for reporting it.

**Comment by mrseanryan** [comment]
related: also cover this:

```
function foo() {
  return (
    <div bar={() => {import("a").then(a => a.used)} />
  );
}
```

**Comment by mrseanryan** [comment]
@jp7837 @pzavolinsky 
hi - I won't have time for this until next weekend.
Hope that is OK. 

Of course, if someone else wants to have a go, be my guest!

Sean
