### ISSUE TITLE
Dynamic import - false positive

### ISSUE THREAD

**Issue by mrseanryan** [pzavolinsky/ts-unused-exports#140]
Dynamic import - false positive:

```
function foo() {
  return (
    <div bar={() => {import("a").then(a => a.used)} />
  );
}
```

**Comment by mrseanryan** [comment]
@jp7837 is the bug, that there is a false positive?

so, `ts-unused-exports` says that `a.used` is *unused* ?

**Comment by jp7837** [comment]
@mrseanryan that’s correct it is saying that a.used is unused.
