### ISSUE TITLE
silently fails when using multiple paths in --excludePathsFromReport

### ISSUE THREAD

**Issue by tconroy** [pzavolinsky/ts-unused-exports#146]
When attempting to exclude multiple paths, ie:

```
--excludePathsFromReport=src/@types;src/__build__
```

fails with the following error:

```
sh: src/__build__: is a directory
```

and `__build__` files are not filtered out of the report, while `@types` files are.

**Comment by tconroy** [comment]
Ah - nevermind. This seems to be a case of [PMAC](https://en.wikipedia.org/wiki/User_error) :) wrapping in quotes fixes it:

```
--excludePathsFromReport='src/@types;src/__build__'
```

**Comment by mrseanryan** [comment]
Ah good - glad it worked out :)
