### ISSUE TITLE
Autofix?

### ISSUE THREAD

**Issue by breck7** [pzavolinsky/ts-unused-exports#157]
Just wanted to say thanks! Great tool. Just found well over 100 unused exports in our project.

Did you have plans for an autofix option? Or is there something already out there that does autofix? I just did about 80 fixes by hand (was very quick, but going forward may be nice to have an autofix). No problem if not, just wondering.

Thanks again! Great stuff.

**Comment by mrseanryan** [comment]
hi @breck7  - appreciate your enthusiasm!

Auto-fix is a topic we have logged in our issues, but not really worked on.

To keep things tidy, I would like to close this issue, as already we have an issue here:

https://github.com/pzavolinsky/ts-unused-exports/issues/93

Feel free to continue the discussion there, if you like.

Regards,
Sean
