### ISSUE TITLE
Make TypeScript a peer dependency

### ISSUE THREAD

**Issue by thewilkybarkid** [pzavolinsky/ts-unused-exports#159]
We've just moved to TypeScript 4, but the library requires 3.8 so both are installed. It appears to work fine at the moment, but it would better if it were a peer dependency so the same version is used (TypeScript 5 syntax, for example, might break it).

**Comment by sverweij** [comment]
Some thoughts:

- As the TypeScript compiler typically will be available already, it also saves a 52Mb download (which is TypeScript's weight a.t.m). This makes ts-unused-exports install a lot lighter (goes from 52Mb to 1Mb)
- With TypeScript as a peer dependency ts-unused-exports would use the same compiler as the environment it's running in, giving the most reliable results. 

However:
- If TypeScript becomes a peer dependency with a lenient range (like >=3.8.3) ts-unused-export's ci should probably have a way to ensure it works (and keeps working) with those versions. That said - setting this up is a doddle on most ci's (see below)
- It could be construed as a breaking change as there might be an environment or two where TypeScript _isn't_ installed in the same location as ts-unused-exports is.
- It also means the Dockerfile (if that's still used) will need to install typescript explicitly as well.

@mrseanryan / @pzavolinsky I've made a [fork](https://github.com/sverweij/ts-unused-exports) of the repo that has the required changes. If you're open to these changes, I can make it into a pull request - just let me know.

In any case there's good news: ts-unused-exports' test suite passes with [flying colors](https://travis-ci.com/github/sverweij/ts-unused-exports) with TypeScript 4 on all node versions.

**Comment by mrseanryan** [comment]
closing - release with 7.0.0 - thank you @sverweij  !
