### ISSUE TITLE
Publish a minor release from master (20 October 2020)

### ISSUE THREAD

**Issue by mrseanryan** [pzavolinsky/ts-unused-exports#169]
@pzavolinsky  I reckon we can make a patch release from master now.

master has these 2 PRs from contributors:

https://github.com/pzavolinsky/ts-unused-exports/pull/166
https://github.com/pzavolinsky/ts-unused-exports/pull/163

I am logging as in issue, for clarity (since had to rebuild both PRs due to the old travis/github issue)

Also a couple of small PRs I merged since they were simple:
https://github.com/pzavolinsky/ts-unused-exports/pull/174
https://github.com/pzavolinsky/ts-unused-exports/pull/175

**Comment by pzavolinsky** [comment]
Done => `6.3.0`
