### ISSUE TITLE
Argument --allowUnusedTypes does not apply to type re-exports

### ISSUE THREAD

**Issue by kachkaev** [pzavolinsky/ts-unused-exports#180]
First things first: fantastic tool 😍 I tried it in a large project yesterday and found so much dead code!

I’d like to report one little issue that I’ve noticed. When I add `--allowUnusedTypes`, I still get reports for types that have been re-exported via `export type { Foo } from "./foo";`. Here is an MWE:

1.  Init the project:

    ```sh
    mkdir ts-unused-exports-false-positives
    cd ts-unused-exports-false-positives
    yarn init --yes
    yarn add -D typescript@4.1.2 ts-unused-exports@7.0.0
    ```

    ```sh
    cat <<EOF >tsconfig.json
    {}
    EOF
    ```

1.  Create TypeScript files

    ```sh
    cat <<EOF >index.ts
    import { fn1 } from "./fn1";
    import { fn2 } from "./fn2";

    console.log(fn1({ x: 1, y: 2 }), fn2({ a: 3, b: 4 }));
    EOF
    ```

    ```sh
    cat <<EOF >fn1.ts
    export interface Fn1Input {
      x: number;
      y: number;
    }

    export const fn1 = (input: Fn1Input): number => input.x + input.y;
    EOF
    ```

    ```sh
    cat <<EOF >fn2/fn2.ts
    export interface Fn2Input {
      a: number;
      b: number;
    }

    export const fn2 = (input: Fn2Input): number => input.a - input.b;
    EOF
    ```

    ```sh
    cat <<EOF >fn2/index.ts
    export { fn2 } from "./fn2";
    export type { Fn2Input } from "./fn2"; // 👈 👀
    EOF
    ```

1.  Run `ts-unused-exports` without `--allowUnusedTypes`

    ```sh
    yarn ts-unused-exports tsconfig.json
    ```

    Output:

    ```txt
    2 modules with unused exports
    /path/to/ts-unused-exports-false-positives/fn1.ts: Fn1Input
    /path/to/ts-unused-exports-false-positives/fn2/index.ts: Fn2Input
    error Command failed with exit code 1.
    ```

    All works as expected.

1.  Run `ts-unused-exports` with `--allowUnusedTypes`

    ```sh
    yarn ts-unused-exports tsconfig.json --allowUnusedTypes
    ```

    Output:

    ```txt
    1 module with unused exports
    /path/to/ts-unused-exports-false-positives/fn2/index.ts: Fn2Input
    error Command failed with exit code 1.
    ```

    Expected output:

    ```txt
    0 modules with unused exports
    ```

In the real scenario, I have functions with React components and interfaces with component props. Re-exports are needed because some components are complex and are therefore put into sub-folders. Having `export type` as an extra line is necessary when the component itself is a default export (it’s not possible to `export * from "./fn2"` in this case).

Happy to help with finding a solution, if needed. Thanks again for the tool 🙌

**Comment by mrseanryan** [comment]
Hi @kachkaev thanks for reporting.

I think this could be solved via https://github.com/pzavolinsky/ts-unused-exports/issues/30

**Comment by mrseanryan** [comment]
TODO:

- add unit or itests to capture the above

- try implementing #30 if that fixes this issue 
I suggest this because it is a general solution (and making it optional behaviour avoids breaking change). 

@kachkaev if you have the time, it would be great to have your contribution!

**Comment by kachkaev** [comment]
Hi @mrseanryan! I think that the proposed `ignoreLocallyUsed` option in #30 is not doing quite the same thing. To me, reporting `export const a` which could be `const a` is a valid feedback. This issue is probably more about suppressing `export type ...` when `--allowUnusedTypes` is on specifically. I’m not familiar with the architecture of `ts-unused-exports` at this point, so I wonder if this approach is at all feasible. From my observations, `--allowUnusedTypes` works well already and the only false positives are when there is `export type { X } from "./someFile"`.

Happy to try contributing with the unit tests.

**Comment by kachkaev** [comment]
I added some broken tests in #181

**Comment by mrseanryan** [comment]
Thank you @kachkaev for contributing 👍

**Comment by mrseanryan** [comment]
@pzavolinsky  we can release this as a `patch` :)
