### ISSUE TITLE
Fix and Automate the release process to speed up development

### ISSUE THREAD

**Issue by mrseanryan** [pzavolinsky/ts-unused-exports#208]
Use github actions to fully automate the release process.

So when a contributor ~~merges to master,~~ opens a PR, the CI tests are run.

Separately, a 'collaborator' can manually execute another github action, to deploy to npm.

This will speed up development, and avoid having PRs waiting for significant time...

**Comment by mrseanryan** [comment]
hi @pzavolinsky  actually now `travis` is broken completely ...

So cannot merge branches to master (since there is a check using travis...)

If you can add me permissions, I would be happy to sort out the build + release,
using `github actions`

Otherwise this project is kinda stuck now ... 😢

**Comment by mrseanryan** [comment]
hi @pzavolinsky   could you please turn OFF the `travis` integration?

As it stops me from merging :(

**Comment by mrseanryan** [comment]
hi @pzavolinsky 
could we just disable the CI?

as it seems too expensive to fix

**Comment by mrseanryan** [comment]
hi @pzavolinsky 
after your email, I suddenly figured out how to `run github action for PRs`

So, at least the "CI" part is working now, via github actions.

The "CD" part could still be nice (deploy to npm...)

**Comment by mrseanryan** [comment]
The CD part (deploy to npm) can be a separate workflow that is only executed manually.

It could also update the changelog with date and version.

**Comment by mrseanryan** [comment]
hi @pzavolinsky 
have pushed fixes to the workflows - regarding #238 

But now there seems to be something blocking the publish to npm

Can you have a look?

Sean

**Comment by pzavolinsky** [comment]
Hey @mrseanryan I removed the `NPM_TOKEN` secret while we did our investigation. I just re-enabled it, try again.

**Comment by mrseanryan** [comment]
hi @pzavolinsky  - now it worked 👍  !

I installed both 8.0.2 and 8.0.3 and the only difference in the package.json files is:

- typescript ^4.0.0 -> ^4.9.3

which seems OK.

If not - let me know, I can change ...

**Comment by mrseanryan** [comment]
Well, I think my deploy 5 failed when the NPM_TOKEN was removed

Then, you added the NPM_TOKEN back.

Then, my deploy 6 succeeded.

Your deploy 7 failed, because that version already publish to npm (8.0.3)

Now, it seems good!

**Comment by pzavolinsky** [comment]
Cool
