### ISSUE TITLE
Default exports are seemingly not marked as used

### ISSUE THREAD

**Issue by shepmaster** [pzavolinsky/ts-unused-exports#22]
[**versions.ts**](https://github.com/integer32llc/rust-playground/blob/d1b1124511bcf2387f56194e3c8b4c8db51880fe/ui/frontend/reducers/versions.ts)

```ts
export default function versions(state = DEFAULT, action: Action) { /* ... */ }
```

[**index.ts**](https://github.com/integer32llc/rust-playground/blob/d1b1124511bcf2387f56194e3c8b4c8db51880fe/ui/frontend/reducers/index.ts)

```ts
import versions, { State as VersionsState } from './versions';

export interface State {
  // ~snip~
  versions: VersionsState;
}

const playgroundApp = combineReducers({
  // ~snip~
  versions,
});

export default playgroundApp;
```

**Comment by pzavolinsky** [comment]
Hi @shepmaster thanks for reporting this. The issue was with default _named_ functions and it's fixed in `2.0.8`.

Cheers!
