### ISSUE TITLE
bug: file ending with 'index.ts' will always be reported as containing unused exports

### ISSUE THREAD

**Issue by wongjiahau** [pzavolinsky/ts-unused-exports#220]
In my project, I have a file where its name ends with `index.ts`. Although all of its exports were imported elsewhere, `ts-unused-exports` reports the file as containing unused exports.

**Comment by neiker** [comment]
Similar issue here, I have a file with the name `index.utils.ts` and is reported as unused after upgrade to v8.0.0 from v7.0.3

**Comment by mrseanryan** [comment]
related to #222
