### ISSUE TITLE
Add `disable-file` option

### ISSUE THREAD

**Issue by ThomasAribart** [pzavolinsky/ts-unused-exports#226]
Hi and thanks for this nice lib!

It would be useful sometimes to disable the unused-exports checks on a whole file, say an `index.ts` or `index.js` that serves as an entry point for other imports, even if said imports don't exist yet.

**Comment by mrseanryan** [comment]
hi @ThomasAribart 
thank you for the suggestion. However, I believe this is already possible with this setting:

ignoreFiles

please see the README for more details. Thank you

**Comment by ThomasAribart** [comment]
@mrseanryan I agree that the goal is the same but the API is completely different. `ignoreFiles` is a CLI option while I'm talking about a file comment. The second API is much more scalable.

**Comment by mrseanryan** [comment]
hm I see - have updated the title.

It seems a bit unusual to exclude files from a tool by adding a comment inside the file.

Also we’d need more specific details

- what would the comment look like?
- is it a whole-line comment?
- is the comment at the too of the file, or is it any random line in the file?


@pzavolinsky what do you think?

**Comment by OfficialCRUGG** [comment]
It's not unusual at all actually.

ESLint allows for disabling it in an entire file using
```ts
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable */
```
or for the next line using
```ts
// eslint-disable-next-line @typescript-eslint/no-unused-vars
```

TypeScript also has
```ts
// @ts-expect-error
// @ts-ignore
```

Or Prettier has
```ts
// prettier-ignore
```
to ignore the next line.
