### ISSUE TITLE
Use compilerOptions.paths from tsconfig.json

### ISSUE THREAD

**Issue by martynsmith** [pzavolinsky/ts-unused-exports#26]
At the moment if I specify path aliases in tsconfig.json it seems that ts-unused-exports doesn't understand them (so things I import using those aliases are marked as unused exports).

Is that something that ts-unused-exports could support?

**Comment by mrseanryan** [comment]
example in `tsconfig.json`

```
"paths": {
    "@modules/*": ["rest/modules/*"],
    "@services/*": ["services/*"]
}
```

**Comment by mrseanryan** [comment]
I think this is fixed in master, via this PR:

https://github.com/pzavolinsky/ts-unused-exports/pull/44

Should be released soon...

**Comment by mrseanryan** [comment]
Closing - this has been fixed - `paths` is now supported.
