### ISSUE TITLE
[Feature request] Only show unused exports that are also unused in the same file

### ISSUE THREAD

**Issue by JasonMan34** [pzavolinsky/ts-unused-exports#280]
Is it possible to add a flag to only show unused exports that are also unused in the same file?  
So this, for example, wouldn't get flagged:
```ts
// This interface is only used in the file
export interface Obi {
  a: string;
  b: string;
}

// This function is used outside
export const logObi = (obi: Obi) => console.log({ obi });
```

**Comment by DLeyland** [comment]
I believe this is a duplicate of https://github.com/pzavolinsky/ts-unused-exports/issues/30. I've just raised https://github.com/pzavolinsky/ts-unused-exports/pull/282 to implement the feature so 🤞 it will be merged soon

**Comment by JasonMan34** [comment]
A duplicate indeed, missed that one
