### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by SharkBaby** [pzavolinsky/ts-unused-exports#291]
node: v14.20.0
when I run below command, I got below error which say `Cannot find module 'typescript'`
`npx ts-unused-exports tsconfig.json`
<img width="815" alt="image" src="https://github.com/pzavolinsky/ts-unused-exports/assets/18545909/dcb88c61-1281-4993-91ab-31f43ada5632">

**Comment by mrseanryan** [comment]
hi @SharkBaby can tou check that TypeScript is installed?

In the README there is an explanation:

| As of version 7.0.0 the TypeScript compiler is a peer dependency of ts-unused-exports. This means that if the TypeScript compiler is not already in the same spot as ts-unused-exports, you have to install it yourself (e.g. with npm i -D typescript).

thank you
