### ISSUE TITLE
Thank you Sean Ryan

### ISSUE THREAD

**Issue by pzavolinsky** [pzavolinsky/ts-unused-exports#306]
Hey @mrseanryan, I wanted to say a big THANK YOU for your dedication to this project.

If it wasn't for you this project would be pretty much abandonware. I was very lucky you joined the project back in late 2019.

I'm grateful you're around, you rock! Thanks so much.

If we ever get to meet in real life I owe you a couple of beers!

I was thinking of sending you an email but I figured a more public message was in order.

Thanks again, Sean!

**Comment by mrseanryan** [comment]
oh you are welcome Patricio, and thank you to all the other contributors!

ideally I’d do more but time is always of the essence…
