### ISSUE TITLE
Option to automatically remove "export" keywords from source code files?

### ISSUE THREAD

**Issue by hi2u** [pzavolinsky/ts-unused-exports#308]
This tool can find all the unnecessary `export` keywords in source code files... can it also delete them for us?

I searched docs and issues etc, but couldn't even see it being mentioned anywhere as a question?

Would be super handy if this could just happen automatically.

**Comment by theo-walton** [comment]
I am also interested in such tool

**Comment by mrseanryan** [comment]
duplicates #93

**Comment by mrseanryan** [comment]
Thanks for logging - we have this already in the list :)
