### ISSUE TITLE
Include file extensions in output

### ISSUE THREAD

**Issue by pelotom** [pzavolinsky/ts-unused-exports#32]
A convenient feature in [iTerm2](https://www.iterm2.com/) is that you can command-click on file paths in the terminal and it will open the file in the appropriate editor. It would be great if this feature could be used with `ts-unused-exports`, but currently the output excludes the `.ts` extension from file names, so they are not actually valid paths.

I'm working around this with `sed` currently:

```
ts-unused-exports ./tsconfig.json | sed -E 's/^(.*):/\1.ts:/'
```

but it would be great if it were supported natively!

**Comment by mrseanryan** [comment]
This is fixed in master - should be released soon
