### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by maartenth** [pzavolinsky/ts-unused-exports#34]
I couldn't use the library because of #29 and a maximum call stack size exceeded error:

```
./node_modules/.bin/ts-unused-exports tsconfig.json src/index.tsx
```

```
RangeError: Maximum call stack size exceeded
    at parsePaths (/.../node_modules/ts-unused-exports/lib/parser.js:201:43)
    at parsePaths (/.../node_modules/ts-unused-exports/lib/parser.js:205:11)
    at parsePaths (/.../node_modules/ts-unused-exports/lib/parser.js:205:11)
    at parsePaths (/.../node_modules/ts-unused-exports/lib/parser.js:205:11)
    (...)
```

**Comment by abirmingham** [comment]
I first ran into a `JavaScript heap out of memory` error. After setting `--max-old-space-size`, I ran into this error. #15 makes me wonder if it is a circular dependency issue. I'm using `circular-dependency-plugin@5.2.0` with no detections but I know of at least one circular dependency that that plugin is missing.

**Comment by mrseanryan** [comment]
In latest code in master, it avoid recursively looking for missing exports.

So that may mitigate this issue.

If you can post an example project somewhere, that would be great?

**Comment by mrseanryan** [comment]
Closing - appears to be resolved.
