### ISSUE TITLE
Handle absolute paths for import statements

### ISSUE THREAD

**Issue by tabansal** [pzavolinsky/ts-unused-exports#37]
I'm using absolute paths to load Components and other files in my project.

Something like

import App, { mapDispatchToProps, mapStateToProps } from "Components/App";

So when I run ts-unused-export it gives all exported members as un-used. Although I'm importing them.

Can you please check on priority basis?

**Comment by mrseanryan** [comment]
Could this be solved via #26 ?

**Comment by mrseanryan** [comment]
I think this is fixed in master, via this PR:

https://github.com/pzavolinsky/ts-unused-exports/pull/44

Should be released soon...

**Comment by mrseanryan** [comment]
Closing, as believe this is fixed.

**Comment by mindaugasnakrosis** [comment]
@tabansal Does absolute paths seem to work for you? If so could you share your minimal tsconfig?

**Comment by mrseanryan** [comment]
@mindaugasnakrosis there is an example here:

https://github.com/pzavolinsky/ts-unused-exports/blob/master/example/with-paths/math.ts

If it is not working - can you please share a simple example of the TypeScript file and also the `tsconfig.json` ?

**Comment by mrseanryan** [comment]
The full example is here, with `tsconfig.json`:

https://github.com/pzavolinsky/ts-unused-exports/tree/master/example/with-paths
