### ISSUE TITLE
analyzeTsConfig not accepting file list as parameter

### ISSUE THREAD

**Issue by KurtPreston** [pzavolinsky/ts-unused-exports#4]
I can get ts-unused-exports to run when I specify files in the `tsconfig.json`.  However, when I try passing in the list of files to `analyzeTsConfig`, I get the error:

```
    The tsconfig does not contain a "files" key:
    Consider either passing an explicit list of files or adding the "files" key.
```

**Comment by pzavolinsky** [comment]
Hi @KurtPreston thanks for reporting this.

I've pushed version `2.0.1` that fixes this issue.

Cheers!
