### ISSUE TITLE
Broken beyond use, false positives everywhere

### ISSUE THREAD

**Issue by jpike88** [pzavolinsky/ts-unused-exports#41]

**Comment by mrseanryan** [comment]
Agree this is a general problem.  
I'd like to add more tests and then reduce the number of false positives. 

It would take a few iterations, but might not ever be completely perfect.

In the mean-time, this PR can help:
https://github.com/pzavolinsky/ts-unused-exports/pull/39

**Comment by mrseanryan** [comment]
Can you provide more details?

Since version `2.1.0` this seems to work much better (using it on a project with 150+k lines of code).

tip: on a large project it can help to exclude `index.ts` files from the output (since they tend to export stuff that is not all used ...)

```
./node_modules/ts-unused-exports/bin/ts-unused-exports ./tsconfig.json --showLineNumber --ignorePaths=index.ts
```

**Comment by jpike88** [comment]
I’m already putting in effort to the fuse box project (which is the bomb) so I can’t contribute. All I know is that this kind of went haywire and I think it needs CI to be a viable idea

**Comment by mrseanryan** [comment]
fuse-box looks great!

>  I think it needs CI to be a viable idea

We're now using travis - is that what you mean?

**Comment by jpike88** [comment]
yeah basically

**Comment by mrseanryan** [comment]
Ok - I think we can close this issue, 
unless something more specific comes up.
