### ISSUE TITLE
Internal: Use Yarn instead of npm for developing this project

### ISSUE THREAD

**Issue by mrseanryan** [pzavolinsky/ts-unused-exports#43]
@pzavolinsky  what about switching to `yarn` instead of `npm` for developing this project?

I find with `npm` the lock file does not work very well, which is somewhat scary.

When i `npm i` I get changes in `package-lock.json`.

With `yarn` I believe the lock is more reliable.

**Comment by pzavolinsky** [comment]
> I find with npm the lock file does not work very well, which is somewhat scary.
True, I believe it changes with different node (and npm) versions. In my experience, changes are usually `dev`, `optional` and `http`/`https` keys (never package versions if they are pinned down). That being said, it is quite annoying indeed.

I've tried `yarn` in the past with other projects and it was OK, although I don't remember anything about lockfile stability (maybe that is a good thing).

Let's give it a try.

**Comment by mrseanryan** [comment]
Update: I've not actually tried moving to yarn, as now npm seems to work fine.

I think it was fixed when we updated dependencies.

**Comment by mrseanryan** [comment]
closing as npm is working fine.
