### ISSUE TITLE
Internal: Consider using semver for publishing and for changelog

### ISSUE THREAD

**Issue by mrseanryan** [pzavolinsky/ts-unused-exports#48]
For developing this package, we could:

- introduce semver - possibly via https://github.com/semantic-release/semantic-release

It helps with versioning, git tags and also the changelog.

**Comment by mrseanryan** [comment]
Related: could auto mate the publishing + update Changelog (with date, version)

@pzavolinsky if it helps I could try to automate that?

But Id need to know what commands you run when publishing

(I don't require npm access, I could do a dry test)

**Comment by pzavolinsky** [comment]
```sh
# edit CHANGELOG.md
# edit package.json and package-lock.json to bump version
git add .
git commit -m 'Bump version to x.x.x'
npm run test
npm pack
# check that the package has no weird stuff, like tests
git push origin HEAD
npm publish
```

**Comment by mrseanryan** [comment]
Ok. At least I could automate the changelog part up to right before the push part.

**Comment by mrseanryan** [comment]
Closing - we have Github actions working.
semver is a bit complex and I think needs commit format?
