### ISSUE TITLE
Trace dependency graph from tsconfig `files`

### ISSUE THREAD

**Issue by OliverJAsh** [pzavolinsky/ts-unused-exports#5]
Hi, first of all, thanks for the fantastic tool.

I noticed that we don't see to trace the dependency graph from tsconfig’s `files`. For example, if you only list `app.ts` and it imports from `math.ts`, any unused exports in `math.ts` will not be reported.

Would it be possible to expand the `files` list to include the whole dependency graph? This is what `tsc` does when compiling, so I would expect similar behaviour from this tool.

**Comment by pzavolinsky** [comment]
Hi @OliverJAsh, thanks!

I just pushed `2.0.3` that now recurses into imports. It _should_ even support cyclic dependencies (although I didn't really tested that scenario).

Cheers!

**Comment by OliverJAsh** [comment]
Amazing, thanks!
