### ISSUE TITLE
Strip comments from `tsconfig`

### ISSUE THREAD

**Issue by OliverJAsh** [pzavolinsky/ts-unused-exports#6]
If `tsconfig.json` contains comments then ts-unused-exports fails, e.g.:

```
SyntaxError: Unexpected token / in JSON at position 245
```

We should strip comments from the config file before parsing it.

**Comment by pzavolinsky** [comment]
Hi @OliverJAsh , pushed version `2.0.2` that supports comments in `tsconfig.json`.

Cheers!
