### ISSUE TITLE
Add CI build (travis?)

### ISSUE THREAD

**Issue by mrseanryan** [pzavolinsky/ts-unused-exports#69]
It could be nice to add CI builds, to auto lint and test branches.

Currently, all such checks are done manually, which is not optimal and can be a bit error-prone.

Also, we could test against multiple Node versions, which is something that is currently not really practical.

@pzavolinsky I've used `travis` on quite a few projects. It seems pretty simple.

If you like to use `travis`, then my understanding is that as the repository owner, you need to be the one to grant `travis` hooks access to this repo.  
After that, I believe I can configure it.

The idea would be to first add a simple `CI` build, that lints, runs unit + itests.

Maybe later, we can make a 'publish' build.

**Comment by mrseanryan** [comment]
related: could add a `coverage` badge and `build passes` badge etc.

**Comment by pzavolinsky** [comment]
I've added Travis CI here: https://github.com/pzavolinsky/ts-unused-exports/pull/71

And you can check build status here: https://travis-ci.com/pzavolinsky/ts-unused-exports

**Comment by pzavolinsky** [comment]
I'm not sure how to add a CC badge, but there must be an easy way to do it.

**Comment by mrseanryan** [comment]
Nice! 
I'll make a PR with badges that seem useful, so you can review. 
For CC badge - it is easy but perhaps could be good to wait until  coverage is higher. 
You link the repo to coveralls.ioAnd the badge is like:```
[![Coveralls](https://img.shields.io/coveralls/mrseanryan/tslint-folders.svg)](https://coveralls.io/github/mrseanryan/tslint-folders)```
I'm hoping to add more tests, to up the coverage... 
Sean

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Nov 2019 at 4:29, Patricio Zavolinsky<notifications@github.com> wrote:   
I'm not sure how to add a CC badge, but there must be an easy way to do it.

**Comment by pzavolinsky** [comment]
> For CC badge - it is easy but perhaps could be good to wait until  coverage is higher. 

:+1:
