### ISSUE TITLE
Add as es-lint rule

### ISSUE THREAD

**Issue by aspirisen** [pzavolinsky/ts-unused-exports#82]
It would be very good if we would have this tool as es-lint rule, so we could have alerts inside our IDE.

**Comment by mrseanryan** [comment]
It would be nice @aspirisen ! - 

There is already a similar issue https://github.com/pzavolinsky/ts-unused-exports/issues/19

Do you mind if we close this one?

**Comment by aspirisen** [comment]
Ok, thanks

**Comment by mrseanryan** [comment]
Duplicate of #19
