### ISSUE TITLE
[Question] Detect exports used only in '.test.ts' files

### ISSUE THREAD

**Issue by mindaugasnakrosis** [pzavolinsky/ts-unused-exports#98]
Is it possible to detect exports used only it test files (code that is no longer used anywhere, just in tests?)

**Comment by mrseanryan** [comment]
No but could be a new optional feature.

Somethong like `--ignoreImportsForTests`

**Comment by mrseanryan** [comment]
@mindaugasnakrosis closing, if that is OK.

Please see #2 where there an existing discussion - keen to hear what you think of the proposed option! 

Sean
